### Understand the code step by step

In [1]:
import numpy as np

In [8]:
input_texts = ['hello Dilan', 'world', 'great to see you', 'never ending']
target_texts = ['bonjour dilan', 'monde', 'content de te voir', 'sans fin']
input_characters = set()
target_characters = set()

In [12]:
max_encoder_seq_length = max([len(txt) for txt in input_texts])
print(max_encoder_seq_length)
min_encoder_seq_length = min([len(txt) for txt in input_texts])
print(min_encoder_seq_length)
max_decoder_seq_length = max([len(txt) for txt in target_texts])

16
5


In [13]:
for input_text in input_texts:
    for char in input_text:
        if char not in input_characters:
            input_characters.add(char)

for target_text in target_texts:
    for char in target_text:
        if char not in target_characters:
            target_characters.add(char)


input_characters = sorted(list(input_characters))
target_characters = sorted(list(target_characters))
print(input_characters)
print(target_characters)
for i, char in enumerate(input_characters):
    print("i, char -> ", i, char)

[' ', 'D', 'a', 'd', 'e', 'g', 'h', 'i', 'l', 'n', 'o', 'r', 's', 't', 'u', 'v', 'w', 'y']
[' ', 'a', 'b', 'c', 'd', 'e', 'f', 'i', 'j', 'l', 'm', 'n', 'o', 'r', 's', 't', 'u', 'v']
i, char ->  0  
i, char ->  1 D
i, char ->  2 a
i, char ->  3 d
i, char ->  4 e
i, char ->  5 g
i, char ->  6 h
i, char ->  7 i
i, char ->  8 l
i, char ->  9 n
i, char ->  10 o
i, char ->  11 r
i, char ->  12 s
i, char ->  13 t
i, char ->  14 u
i, char ->  15 v
i, char ->  16 w
i, char ->  17 y


In [14]:
input_token_index = dict([char, i] for i, char in enumerate(input_characters))
target_token_index = dict([char, i] for i, char in enumerate(target_characters))

print("input_token_index -> ", input_token_index)
print("target_token_index -> ", target_token_index)


input_token_index ->  {' ': 0, 'D': 1, 'a': 2, 'd': 3, 'e': 4, 'g': 5, 'h': 6, 'i': 7, 'l': 8, 'n': 9, 'o': 10, 'r': 11, 's': 12, 't': 13, 'u': 14, 'v': 15, 'w': 16, 'y': 17}
target_token_index ->  {' ': 0, 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'i': 7, 'j': 8, 'l': 9, 'm': 10, 'n': 11, 'o': 12, 'r': 13, 's': 14, 't': 15, 'u': 16, 'v': 17}


In [16]:
num_encoder_tokens = len(input_characters)
num_decoder_tokens = len(target_characters)

encoder_input_data = np.zeros((len(input_texts), max_encoder_seq_length, num_encoder_tokens), dtype="float32")
decoder_input_data = np.zeros((len(input_texts), max_decoder_seq_length, num_decoder_tokens), dtype="float32")
decoder_target_data = np.zeros((len(input_texts), max_decoder_seq_length, num_decoder_tokens), dtype="float32")

print("input texts length -> ", len(input_texts))
print("max encoder seq length -> ", max_encoder_seq_length)
print("num encoder tokens -> ", num_encoder_tokens)
print(encoder_input_data) # prints 4x16x17 array of zeros
#meaning -> 4 dimensions, 16 rows & 17 columns

input texts length ->  4
max encoder seq length ->  16
num encoder tokens ->  18
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [17]:
print(tuple(zip(input_texts, target_texts)))

(('hello Dilan', 'bonjour dilan'), ('world', 'monde'), ('great to see you', 'content de te voir'), ('never ending', 'sans fin'))
